#!/usr/bin/env python3
"""list_achievements.py - generate the achievement catalog tables from meta.yaml.

``meta.yaml`` files are the single source of truth. The tables in ``README.md``
and ``_docs/ACHIEVEMENT_INDEX.md`` are generated from them so they cannot drift.
This script renders those tables and, with ``--check``, fails when the committed
markdown no longer matches what the catalog implies. That makes the sync
requirement in ACHIEVEMENT_INDEX.md enforceable instead of aspirational.

Usage:
    python list_achievements.py                 # print all tables
    python list_achievements.py --which index   # only the index table
    python list_achievements.py --check         # verify markdown is in sync
    python list_achievements.py --json          # dump the catalog as JSON

Exit codes:
    0  success (and, with --check, markdown is in sync)
    1  catalog could not be read
    2  --check found out-of-sync markdown
"""
from __future__ import annotations

import argparse
import contextlib
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)
ACHIEVEMENTS_DIR = os.path.join(REPO_ROOT, "_achievements")
README_PATH = os.path.join(REPO_ROOT, "README.md")
INDEX_PATH = os.path.join(REPO_ROOT, "_docs", "ACHIEVEMENT_INDEX.md")

BEGIN_INDEX = "<!-- BEGIN:ACHIEVEMENT_INDEX (generated by _scripts/list_achievements.py) -->"
END_INDEX = "<!-- END:ACHIEVEMENT_INDEX -->"
BEGIN_CATALOG = "<!-- BEGIN:ACHIEVEMENT_CATALOG (generated by _scripts/list_achievements.py) -->"
END_CATALOG = "<!-- END:ACHIEVEMENT_CATALOG -->"

YAML_HINT = "PyYAML is required: pip install -r requirements.txt"

# Kept identical to grant_check.VALID_STATUSES; a test asserts they agree so the
# two tools cannot drift into disagreeing about what a valid status is.
VALID_STATUSES = {"Not yet", "In progress", "Earned", "Deprecated", "Unobtainable"}
VALID_EARNABLE = {True, False}


class CatalogError(RuntimeError):
    """Raised when the catalog cannot be read or a meta.yaml is malformed."""


def _load_yaml(path: str) -> dict:
    """Parse one meta.yaml.

    PyYAML is required rather than hand-rolled. meta.yaml files nest blocks
    (``tiers:``, ``links:``, ``verified:``) and mix scalars with sequence items,
    and a partial parser that quietly mis-reads ``earnable: true`` as the string
    ``"true"`` would corrupt the generated tables while still exiting zero.
    """
    try:
        import yaml
    except ImportError as exc:
        raise CatalogError(f"{path}: cannot import yaml. {YAML_HINT}") from exc
    try:
        with open(path, encoding="utf-8") as handle:
            data = yaml.safe_load(handle)
    except yaml.YAMLError as exc:
        raise CatalogError(f"{path}: invalid YAML: {exc}") from exc
    if not isinstance(data, dict):
        raise CatalogError(f"{path}: expected a YAML mapping at the top level")
    return data


def iter_meta_files(achievements_dir: str = ACHIEVEMENTS_DIR):
    for dirpath, dirnames, filenames in os.walk(achievements_dir):
        dirnames[:] = sorted(d for d in dirnames if d != "__pycache__")
        if "meta.yaml" in filenames:
            yield os.path.join(dirpath, "meta.yaml")


def load_catalog(achievements_dir: str = ACHIEVEMENTS_DIR) -> list[dict]:
    """Load and validate every meta.yaml under the catalog root.

    Validation happens here rather than only at render time because the output of
    this function is written into committed markdown: a typo would otherwise be
    published to the README before any tool noticed.
    """
    records: list[dict] = []
    for path in sorted(iter_meta_files(achievements_dir)):
        data = _load_yaml(path)
        slug = data.get("slug")
        if not slug:
            raise CatalogError(f"{path}: missing required 'slug'")

        folder = os.path.basename(os.path.dirname(path))
        if slug != folder:
            raise CatalogError(
                f"{path}: slug {slug!r} does not match its folder name {folder!r}. "
                "ACHIEVEMENT_FORMAT.md requires them to be identical, and the "
                "generated README link is derived from the slug."
            )

        status = data.get("status")
        if status not in VALID_STATUSES:
            raise CatalogError(
                f"{path}: status {status!r} is not one of {sorted(VALID_STATUSES)}"
            )

        earnable = data.get("earnable")
        if earnable not in VALID_EARNABLE:
            raise CatalogError(
                f"{path}: earnable {earnable!r} must be a YAML boolean "
                "(true or false), not a string"
            )

        tiers = data.get("tiers") or []
        tier_names = [t.get("name", "?") for t in tiers if isinstance(t, dict)]
        records.append(
            {
                "slug": slug,
                "name": data.get("name", slug),
                "emoji": data.get("emoji", ""),
                "status": status,
                "earnable": earnable,
                "difficulty": data.get("automation_difficulty", "(missing)"),
                "how_earned": data.get("how_earned", ""),
                "automatable": data.get("automatable", "(missing)"),
                "tier_names": tier_names,
                "tier_count": len(tier_names),
                "verified": data.get("verified") or {},
                "earned_on": data.get("earned_on") or [],
                "group": _group_of(path, achievements_dir),
                "path": os.path.relpath(path, achievements_dir).replace("\\", "/"),
            }
        )
    if not records:
        raise CatalogError(f"no meta.yaml files found under {achievements_dir}")
    return records


def _group_of(path: str, achievements_dir: str) -> str:
    """Bucket a meta.yaml by its first path segment under _achievements/.

    ``_achievements/starstruck`` -> ``active``
    ``_achievements/_deprecated/mars-2020`` -> ``_deprecated``
    """
    rel = os.path.relpath(os.path.dirname(path), achievements_dir).replace("\\", "/")
    if rel in {".", ""}:
        return "active"
    head = rel.split("/", 1)[0]
    return head if head.startswith("_") else "active"


def render_index_table(records: list[dict]) -> str:
    rows = [
        "| # | Slug | Name | Tier count | Earnable? | Status |",
        "|---|---|---|---|---|---|",
    ]
    for i, rec in enumerate(records, 1):
        earnable = {True: "Yes", False: "**No** (frozen)"}.get(rec["earnable"], "Yes")
        rows.append(
            f"| {i} | `{rec['slug']}` | {rec['name']} | {rec['tier_count']} "
            f"| {earnable} | {rec['status']} |"
        )
    return "\n".join(rows)


def render_catalog_table(records: list[dict]) -> str:
    rows = [
        "| Slug | Name | Tier(s) | Status | Difficulty | Easiest path |",
        "|---|---|---|---|---|---|",
    ]
    for rec in records:
        if rec["group"] != "active":
            continue
        tiers = " → ".join(rec["tier_names"]) if rec["tier_names"] else "1"
        path = f"./_achievements/{rec['slug']}/README.md"
        rows.append(
            f"| [{rec['emoji']} {rec['name']}]({path}) | {rec['name']} | {tiers} "
            f"| **{rec['status']}** | {rec['difficulty']} | {rec['how_earned']} |"
        )
    return "\n".join(rows)


def _block_pattern(begin: str, end: str) -> re.Pattern[str]:
    return re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)


def replace_block(text: str, begin: str, end: str, body: str) -> str:
    pattern = _block_pattern(begin, end)
    replacement = f"{begin}\n{body}\n{end}"
    if pattern.search(text):
        return pattern.sub(lambda _: replacement, text)
    return text


def has_block(text: str, begin: str, end: str) -> bool:
    """True when a well-formed begin..end region is present and matchable.

    Both markers being present is not sufficient: if they appear in the wrong
    order the non-greedy pattern cannot match, and ``replace_block`` would return
    the text unchanged. Callers must distinguish that from "already in sync", or
    ``--check`` silently passes and ``--write`` silently does nothing.
    """
    return _block_pattern(begin, end).search(text) is not None


def _targets(records: list[dict]) -> list[tuple[str, str, str, str]]:
    """The (path, begin, end, body) pairs shared by --check and --write."""
    return [
        (README_PATH, BEGIN_CATALOG, END_CATALOG, render_catalog_table(records)),
        (INDEX_PATH, BEGIN_INDEX, END_INDEX, render_index_table(records)),
    ]


def check_sync(records: list[dict]) -> list[str]:
    problems: list[str] = []
    for path, begin, end, body in _targets(records):
        rel = os.path.relpath(path, REPO_ROOT)
        if not os.path.isfile(path):
            problems.append(f"{rel}: missing")
            continue
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
        if begin not in text or end not in text:
            problems.append(f"{rel}: missing generated block markers")
            continue
        if not has_block(text, begin, end):
            problems.append(
                f"{rel}: markers are present but do not form a begin..end region "
                "(misordered or duplicated). --check cannot verify and --write "
                "would be a no-op; fix the marker order by hand."
            )
            continue
        if replace_block(text, begin, end, body) != text:
            problems.append(
                f"{rel}: table is out of sync, run "
                f"'python _scripts/list_achievements.py --write'"
            )
    return problems


def write_tables(records: list[dict]) -> list[str]:
    written: list[str] = []
    for path, begin, end, body in _targets(records):
        if not os.path.isfile(path):
            raise CatalogError(f"cannot write {path}: file does not exist")
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
        updated = replace_block(text, begin, end, body)
        if updated != text:
            with open(path, "w", encoding="utf-8", newline="\n") as handle:
                handle.write(updated)
            written.append(os.path.relpath(path, REPO_ROOT))
    return written


def _use_utf8_output() -> None:
    """Make emoji-bearing output safe on legacy Windows consoles.

    Achievement names carry emoji (⭐, 🧠, 🔫). Windows still defaults some
    consoles to cp1252, which raises UnicodeEncodeError on those characters.
    """
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is None:
            continue
        with contextlib.suppress(ValueError, OSError):
            reconfigure(encoding="utf-8", errors="replace")


def main(argv: list[str] | None = None) -> int:
    _use_utf8_output()
    parser = argparse.ArgumentParser(description="Render the achievement catalog tables.")
    parser.add_argument(
        "--which",
        choices=["all", "index", "catalog"],
        default="all",
        help="which table to print",
    )
    parser.add_argument("--catalog", default=ACHIEVEMENTS_DIR)
    # --check, --write and --json are three different modes. Without exclusivity,
    # `--json --check` silently ignores --check because --json returns first.
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="verify markdown is in sync")
    mode.add_argument("--write", action="store_true", help="rewrite the generated blocks")
    mode.add_argument("--json", action="store_true", help="dump the catalog as JSON")
    args = parser.parse_args(argv)

    try:
        records = load_catalog(args.catalog)
    except CatalogError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if args.json:
        print(json.dumps(records, indent=2, ensure_ascii=False))
        return 0

    if args.write:
        try:
            written = write_tables(records)
        except CatalogError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1
        if written:
            for path in written:
                print(f"updated {path}")
        else:
            print("already in sync")
        return 0

    if args.check:
        problems = check_sync(records)
        if problems:
            print("OUT OF SYNC:")
            for problem in problems:
                print(f"  - {problem}")
            return 2
        print("OK: catalog markdown is in sync")
        return 0

    if args.which in {"all", "catalog"}:
        print(render_catalog_table(records))
        print()
    if args.which in {"all", "index"}:
        print(render_index_table(records))
    return 0


if __name__ == "__main__":
    sys.exit(main())
