#!/usr/bin/env python3
"""list_achievements.py — load, validate and publish the achievement catalog.

`_achievements/<slug>/meta.yaml` is the source of truth. Everything else in this
repository that presents the catalog is a projection of it: the table in
`README.md`, the table in `_docs/ACHIEVEMENT_INDEX.md`, and the JSON snapshot
`--json` emits. This script is the only thing that writes those projections,
which is what makes "the markdown is in sync" a checkable claim rather than a
convention.

Three modes, and they are mutually exclusive because they answer different
questions:

    --check   is the committed markdown still a faithful projection?
    --write   regenerate the markdown from the catalog
    --json    emit the catalog for another tool to consume

Exit codes are load-bearing in CI:

    0   the catalog is valid and the markdown agrees with it
    1   the catalog is invalid, or a target file is unwritable
    2   valid catalog, stale markdown

Usage:
    python _scripts/list_achievements.py --check
    python _scripts/list_achievements.py --write
    python _scripts/list_achievements.py --json
    python _scripts/list_achievements.py --check --catalog /tmp/somewhere
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from contextlib import suppress
from pathlib import Path

# Ensure stdout can print emoji on Windows (default cp1252 cannot).
with suppress(AttributeError, ValueError):
    sys.stdout.reconfigure(encoding="utf-8")

SCRIPT_DIR = Path(__file__).parent.resolve()
REPO_ROOT = SCRIPT_DIR.parent
ACHIEVEMENTS_DIR = REPO_ROOT / "_achievements"
SCHEMA_PATH = REPO_ROOT / "_docs" / "meta.schema.json"

# Kept as module attributes rather than locals because the tests rebind
# `la.README_PATH` and `la.INDEX_PATH` to point at a temporary tree. A function
# that captured the value at import time would keep writing to the real repo.
README_PATH = str(REPO_ROOT / "README.md")
INDEX_PATH = str(REPO_ROOT / "_docs" / "ACHIEVEMENT_INDEX.md")

# The markers delimit the generated regions. They are HTML comments so the files
# still render on github.com, and they are searched for as exact strings so that
# a file missing one is reported rather than silently half-regenerated.
BEGIN_CATALOG = "<!-- BEGIN:ACHIEVEMENT_CATALOG (generated by _scripts/list_achievements.py) -->"
END_CATALOG = "<!-- END:ACHIEVEMENT_CATALOG -->"
BEGIN_INDEX = "<!-- BEGIN:ACHIEVEMENT_INDEX (generated by _scripts/list_achievements.py) -->"
END_INDEX = "<!-- END:ACHIEVEMENT_INDEX -->"

# The documented status vocabulary. `grant_check.py` holds its own copy because
# it must classify a status it is told about rather than one it loaded, and a
# test asserts the two agree - a catalog that can express a status the auditor
# cannot classify would report drift on a status nobody wrote.
VALID_STATUSES = {"Not yet", "In progress", "Earned", "Deprecated", "Unobtainable"}

# Group name -> the directory that holds it. `active` achievements sit directly
# under `_achievements/`; the other two are category containers.
GROUPS = ("active", "_deprecated", "_highlights")


class CatalogError(Exception):
    """A catalog entry is malformed, or a target is unwritable.

    Distinct from a traceback because these are expected, actionable conditions:
    someone hand-edited a `meta.yaml`, or moved a file. Both need a message
    naming the file and the fix, not a stack trace.
    """


def _load_yaml(path: str | os.PathLike) -> dict:
    """Read one YAML file into a dict, or raise CatalogError saying why not.

    ImportError is caught and re-raised as something actionable on purpose.
    PyYAML is the one dependency that is genuinely easy to be missing, and
    "No module named 'yaml'" is not an answer - `pip install` is.
    """
    try:
        import yaml
    except ImportError as exc:  # pragma: no cover - exercised via patched import
        raise CatalogError(
            f"PyYAML is required to read {path}. Install it with "
            f"`pip install -r requirements.txt` (or `pip install pyyaml`)."
        ) from exc

    try:
        with open(path, encoding="utf-8") as handle:
            data = yaml.safe_load(handle)
    except yaml.YAMLError as exc:
        raise CatalogError(f"{path}: invalid YAML - {exc}") from exc

    # A meta.yaml that parses to a list, or to None because it is empty, is not
    # a catalog entry. Checking `isinstance` is what stops a stray `- item`
    # list being treated as a mapping and failing later with a confusing
    # KeyError three functions away.
    if not isinstance(data, dict):
        raise CatalogError(
            f"{path}: expected a mapping of fields, got {type(data).__name__}"
        )
    return data


def _validate_entry(data: dict, folder: Path, slug_dir: Path) -> None:
    """`folder` is the achievement's own directory; `slug_dir` is the same path
    and is kept only so the error messages name the file that needs editing."""
    """Reject an entry that would produce a misleading table.

    Every message here names the field and what was wrong with it, because the
    person who has to fix it is editing YAML by hand and will read the CI log
    rather than this file.
    """
    slug = data.get("slug")
    if not isinstance(slug, str) or not slug:
        raise CatalogError(f"{slug_dir / 'meta.yaml'}: missing required field 'slug'")
    if slug != folder.name:
        raise CatalogError(
            f"{slug_dir / 'meta.yaml'}: slug {slug!r} does not match its folder "
            f"name {folder.name!r}. Rename one or the other - they are used as "
            f"join keys everywhere else."
        )

    status = data.get("status")
    if status not in VALID_STATUSES:
        raise CatalogError(
            f"{slug_dir / 'meta.yaml'}: status {status!r} is not one of "
            f"{sorted(VALID_STATUSES)}"
        )

    earnable = data.get("earnable")
    # Checked by type rather than truthiness. `earnable: 'true'` is truthy, so a
    # quoted value would pass a truthiness check and then be rendered into the
    # markdown as if it were a real boolean. A string here is a quoting mistake
    # upstream, and quoting mistakes are worth naming rather than accommodating.
    if not isinstance(earnable, bool):
        raise CatalogError(
            f"{slug_dir / 'meta.yaml'}: earnable must be a YAML boolean "
            f"(true/false), got {earnable!r}"
        )

    name = data.get("name")
    if not isinstance(name, str) or not name:
        raise CatalogError(f"{slug_dir / 'meta.yaml'}: missing required field 'name'")

    tiers = data.get("tiers", [])
    if not isinstance(tiers, list):
        raise CatalogError(
            f"{slug_dir / 'meta.yaml'}: tiers must be a list, got {type(tiers).__name__}"
        )


def _slug_dirs(base: Path) -> list[tuple[str, Path, Path]]:
    """Yield (group, folder, slug_dir) for every achievement under `base`.

    Walks one level into the `_`-prefixed category containers and treats
    immediate children of `base` as `active`. A folder is an achievement only if
    it has a `meta.yaml`; anything else under those directories is not part of
    the catalog.
    """
    found: list[tuple[str, Path, Path]] = []
    if not base.is_dir():
        raise CatalogError(f"catalog directory does not exist: {base}")
    for entry in sorted(base.iterdir()):
        if not entry.is_dir() or entry.name.startswith("."):
            continue
        if entry.name.startswith("_"):
            if entry.name not in GROUPS:
                raise CatalogError(
                    f"{entry}: unknown group directory. Expected one of {list(GROUPS)}"
                )
            for sub in sorted(entry.iterdir()):
                if sub.is_dir() and (sub / "meta.yaml").exists():
                    # The slug directory is `sub` itself, not the group
                    # container. Matching `slug:` against the container name is
                    # how "arctic-code-vault does not match its folder
                    # name '_deprecated'" gets reported for every entry that
                    # lives under a category directory.
                    found.append((entry.name, sub, sub))
        elif (entry / "meta.yaml").exists():
            found.append(("active", entry, entry))
    return found


def load_catalog(base: str | os.PathLike | None = None) -> list[dict]:
    """Load every catalog entry as a dict, sorted for a stable rendering.

    Raises CatalogError on the first malformed entry. That is deliberate: a
    catalog with one bad file is not partially usable, and reporting every
    problem at once would mean loading what it can and then rendering a table
    that silently omits the rest.
    """
    root = Path(base) if base is not None else ACHIEVEMENTS_DIR
    records: list[dict] = []
    for group, slug_dir, container in _slug_dirs(root):
        data = _load_yaml(slug_dir / "meta.yaml")
        _validate_entry(data, container, slug_dir)
        tiers = data.get("tiers", [])
        records.append(
            {
                "slug": data["slug"],
                "name": data["name"],
                "emoji": data.get("emoji", ""),
                "status": data["status"],
                "earnable": data["earnable"],
                "group": group,
                # Both fields are part of the catalog and both are load-bearing:
                # `automatable` is the retraction guard for Galaxy Brain (VULN-006,
                # where a published claim of automation turned out to be false), and
                # `automation_difficulty` is what the difficulty column renders.
                # Coerced to a real boolean so a consumer does not have to guess
                # whether "false" is a string or a value.
                "automatable": data.get("automatable") is True,
                "difficulty": data.get("automation_difficulty", ""),
                "how_earned": _how_earned(data),
                "tier_names": [t.get("name", "?") for t in tiers],
                "tier_count": len(tiers),
                "verified": data.get("verified"),
                "earned_on": data.get("earned_on") or [],
                "deprecated_reason": data.get("deprecated_reason"),
                "path": str(
                    (slug_dir / "meta.yaml").relative_to(root.parent)
                    if root.parent in slug_dir.parents
                    else slug_dir / "meta.yaml"
                ),
            }
        )

    # Sort by group order, then by name. Sorting by group first is what lets
    # render_catalog_table take a plain slice of `active` records and get a
    # complete, correctly-ordered subset without re-deriving the order.
    group_rank = {name: index for index, name in enumerate(GROUPS)}
    records.sort(key=lambda r: (group_rank.get(r["group"], 99), r["name"].lower()))
    return records


def _how_earned(data: dict) -> str:
    """One-line summary of how to earn it, for the index table."""
    how = data.get("how_earned")
    if isinstance(how, str):
        return how
    if isinstance(how, list) and how:
        return str(how[0])
    return ""


def _tier_label(record: dict) -> str:
    """Render a tier list as `Default → Gold`, or `Frozen` for a deprecated one."""
    names = record["tier_names"]
    if not names:
        return "?"
    if len(names) == 1:
        return names[0]
    return " → ".join(names)


def _status_label(record: dict) -> str:
    """The status cell, annotated where the catalog says more."""
    status = record["status"]
    verified = record.get("verified")
    if status == "Earned" and isinstance(verified, dict):
        parts = []
        tier = verified.get("tier")
        count = verified.get("repeat_count")
        if tier:
            parts.append(tier)
        if count:
            parts.append(f"x{count}")
        detail = f" ({', '.join(parts)})" if parts else ""
        return f"**Earned** ✅{detail}"
    if status == "Deprecated" and record.get("deprecated_reason"):
        return f"**Deprecated** — {record['deprecated_reason']}"
    return f"**{status}**"


def render_catalog_table(records: list[dict]) -> str:
    """The README table: active achievements only.

    Deprecated and highlight badges are excluded on purpose. The README's table
    is the "what is there" view, and mixing in four account-tier badges that
    cannot be earned by activity dilutes it; `_docs/ACHIEVEMENT_INDEX.md` is the
    complete view and lists everything.
    """
    active = [r for r in records if r["group"] == "active"]
    lines = [
        "| Slug | Name | Tier(s) | Status | Difficulty | Easiest path |",
        "|---|---|---|---|---|---|",
    ]
    for record in active:
        lines.append(
            "| [{slug}](./_achievements/{slug}/README.md) | {emoji} {name} | "
            "{tiers} | {status} | {difficulty} | {how} |".format(
                slug=record["slug"],
                emoji=record["emoji"],
                name=record["name"],
                tiers=_tier_label(record),
                status=_status_label(record),
                difficulty=record["difficulty"] or "—",
                how=record["how_earned"] or "—",
            )
        )
    return "\n".join(lines)


def render_index_table(records: list[dict]) -> str:
    """The index table: every record, grouped by category."""
    lines = [
        "| Slug | Name | Group | Tier(s) | Status | Earnable |",
        "|---|---|---|---|---|---|",
    ]
    for record in records:
        lines.append(
            "| `{slug}` | {emoji} {name} | {group} | {tiers} | {status} | {earnable} |".format(
                slug=record["slug"],
                emoji=record["emoji"],
                name=record["name"],
                group=record["group"],
                tiers=_tier_label(record),
                status=record["status"],
                earnable="Yes" if record["earnable"] else "No",
            )
        )
    return "\n".join(lines)


def has_block(text: str, begin: str, end: str) -> bool:
    """True when `begin` precedes `end` in `text`.

    Order is the whole point. A file containing the two markers in the wrong
    order has no generated region in it, and treating that as "in sync" is how
    a stale table survives a check that looks like it is guarding it.
    """
    begin_at = text.find(begin)
    end_at = text.find(end)
    if begin_at < 0 or end_at < 0:
        return False
    return begin_at < end_at


def replace_block(text: str, begin: str, end: str, body: str) -> str:
    """Replace the generated region between `begin` and `end` with `body`.

    Idempotent: running it twice on the same input produces the same output,
    which is what makes `--write` safe to run on a clean tree.

    Returns `text` unchanged when the markers are absent or misordered. Refusing
    to guess is the right call - appending a second copy of a generated table to
    a file that does not have the markers would produce a document that reads as
    if it had two different answers to the same question.
    """
    begin_at = text.find(begin)
    end_at = text.find(end)
    if begin_at < 0 or end_at < 0 or end_at < begin_at:
        return text
    return text[: begin_at + len(begin)] + "\n" + body + "\n" + text[end_at:]


def check_sync(records: list[dict]) -> list[str]:
    """Return a list of human-readable drift descriptions; empty means in sync.

    Distinguishes "the markers are missing or misordered" from "the markers are
    fine but the content is stale", because the fixes are different: the first
    needs a human to add the markers, the second is just `--write`.
    """
    problems: list[str] = []
    expected = (
        (README_PATH, BEGIN_CATALOG, END_CATALOG, render_catalog_table(records)),
        (INDEX_PATH, BEGIN_INDEX, END_INDEX, render_index_table(records)),
    )
    for path, begin, end, wanted in expected:
        label = os.path.basename(path)
        try:
            with open(path, encoding="utf-8") as handle:
                text = handle.read()
        except FileNotFoundError:
            problems.append(f"{label}: file does not exist")
            continue

        if not has_block(text, begin, end):
            if text.find(begin) >= 0 and text.find(end) >= 0:
                # Both markers present but in the wrong order. Reported
                # separately from a missing block because the fix differs: this
                # needs a human to move a line, whereas a missing block needs
                # the markers added. Either way the content is also stale, so
                # both facts are stated.
                problems.append(
                    f"{label}: markers are present but misordered, so the "
                    f"catalog table is out of sync; move {end} below {begin}"
                )
            else:
                problems.append(
                    f"{label}: missing the generated block, so the catalog table "
                    f"is out of sync; add {begin} followed by {end}"
                )
            continue

        got = replace_block(text, begin, end, wanted)
        if got != text:
            problems.append(
                f"{label}: catalog table is out of sync with _achievements/*/meta.yaml"
            )
    return problems


def write_tables(records: list[dict]) -> list[str]:
    """Write both generated regions. Returns the paths changed."""
    changed: list[str] = []
    targets = (
        (README_PATH, BEGIN_CATALOG, END_CATALOG, render_catalog_table(records)),
        (INDEX_PATH, BEGIN_INDEX, END_INDEX, render_index_table(records)),
    )
    for path, begin, end, body in targets:
        if not os.path.isfile(path):
            raise CatalogError(
                f"cannot write {path}: the target does not exist. The generated "
                f"region is only ever written into an existing file, so this is "
                f"almost always a wrong working directory rather than a missing "
                f"file."
            )
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
        if not has_block(text, begin, end):
            raise CatalogError(
                f"cannot write {path}: {begin} and {end} are not both present, "
                f"or are out of order"
            )
        updated = replace_block(text, begin, end, body)
        if updated != text:
            # newline="" because on Windows the default newline translation would
            # rewrite every LF in the file as CRLF, turning a one-block change
            # into a whole-file diff.
            with open(path, "w", encoding="utf-8", newline="") as handle:
                handle.write(updated)
            changed.append(path)
    return changed


def load_schema() -> dict:
    with open(SCHEMA_PATH, encoding="utf-8") as handle:
        return json.load(handle)


def validate_schema(base: str | os.PathLike | None = None) -> list[str]:
    """Strict JSON Schema validation of every meta.yaml, source fields only.

    Reads the files rather than the records from `load_catalog`, because
    `_docs/meta.schema.json` describes the source document: it has
    `additionalProperties: false`, so validating a projection reports
    "tier_names is an additional property" for every field the loader
    legitimately derives, and re-listing `automation_difficulty` under the name
    the table renders it as. Both are complaints about the projection, not
    about the data, and a validator that reports those is a validator nobody
    will read.
    """
    try:
        import jsonschema
    except ImportError:
        return [
            "jsonschema not installed - run `pip install -r requirements.txt` "
            "for strict validation"
        ]
    try:
        schema = load_schema()
    except (FileNotFoundError, json.JSONDecodeError) as exc:
        return [f"cannot load schema at {SCHEMA_PATH}: {exc}"]

    root = Path(base) if base is not None else ACHIEVEMENTS_DIR
    validator = jsonschema.Draft202012Validator(schema)
    problems: list[str] = []
    for meta_path in sorted(root.rglob("meta.yaml")):
        try:
            data = _load_yaml(meta_path)
        except CatalogError as exc:
            problems.append(str(exc))
            continue
        for err in sorted(validator.iter_errors(data), key=lambda e: list(e.path)):
            loc = ".".join(str(p) for p in err.absolute_path) or "<root>"
            problems.append(f"{data.get('slug', meta_path.parent.name)} → {loc}: {err.message}")
    return problems


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Load _achievements/*/meta.yaml and either check or regenerate the "
            "catalog tables in README.md and _docs/ACHIEVEMENT_INDEX.md."
        )
    )
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument(
        "--check",
        action="store_true",
        help="Exit 2 if the committed markdown is not a faithful projection.",
    )
    modes.add_argument(
        "--write",
        action="store_true",
        help="Rewrite the generated regions from the catalog.",
    )
    modes.add_argument(
        "--json",
        action="store_true",
        help="Print the catalog as JSON on stdout and nothing else.",
    )
    parser.add_argument(
        "--catalog",
        default=None,
        metavar="DIR",
        help="Catalog root to read (default: the repository's _achievements).",
    )
    parser.add_argument(
        "--validate-schema",
        action="store_true",
        help="Additionally validate every entry against _docs/meta.schema.json.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """Entry point. Returns the exit code rather than raising SystemExit, so the
    behaviour is directly testable; argparse still raises SystemExit for a usage
    error, which is the right thing for a CLI."""
    parser = _build_parser()
    args = parser.parse_args(argv)

    try:
        records = load_catalog(args.catalog)
    except CatalogError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if args.validate_schema:
        problems = validate_schema(args.catalog)
        if problems:
            for problem in problems:
                print(f"error: {problem}", file=sys.stderr)
            return 1

    if args.json:
        # JSON on stdout and nothing else, so `--json | jq` works.
        print(json.dumps(records, indent=2, ensure_ascii=False, default=str))
        return 0

    if args.check:
        # stdout, not stderr: tests/test_scripts.py asserts on the captured
        # stdout for both the clean and the drifted case, and a test that reads
        # the wrong stream is not a test. `--json` is the mode that has to keep
        # stdout pure, and it does - it returns before reaching here.
        problems = check_sync(records)
        if problems:
            print(
                f"OUT OF SYNC: {len(records)} achievement(s) loaded, "
                f"{len(problems)} file(s) stale:",
                file=sys.stdout,
            )
            for problem in problems:
                print(f"  - {problem}", file=sys.stdout)
            print(
                "Regenerate with `python _scripts/list_achievements.py --write`.",
                file=sys.stdout,
            )
            return 2
        print(
            f"OK: {len(records)} achievements validated; catalog tables are in sync.",
            file=sys.stdout,
        )
        return 0

    if args.write:
        try:
            changed = write_tables(records)
        except CatalogError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1
        if changed:
            for path in changed:
                print(f"wrote {path}", file=sys.stdout)
        else:
            print("already up to date; nothing written.", file=sys.stdout)
        return 0

    # Default: print the catalog table to stdout without touching any file.
    print(render_index_table(records))
    return 0


if __name__ == "__main__":
    sys.exit(main())